/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import tubeslokeritera.koneksi;

/**
 *
 * @author asus
 */
public class Register extends javax.swing.JFrame {
    Connection connect = koneksi.getKoneksi();
    ResultSet r = null;
    PreparedStatement p = null;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new javax.swing.JPanel();
        bcklocker = new javax.swing.JPanel();
        lokeritera = new javax.swing.JLabel();
        nadep = new javax.swing.JLabel();
        almt = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        nabel = new javax.swing.JLabel();
        jekel = new javax.swing.JLabel();
        phon = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        namablkng = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        namadep = new javax.swing.JTextField();
        alamatt = new javax.swing.JTextField();
        emaill = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        jenkel = new javax.swing.JComboBox<>();
        usname1 = new javax.swing.JLabel();
        daftar1 = new javax.swing.JButton();
        pwdd = new javax.swing.JPasswordField();
        repass = new javax.swing.JPasswordField();
        close = new javax.swing.JLabel();
        retype = new javax.swing.JLabel();
        bckutama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lokeritera.setBackground(new java.awt.Color(0, 0, 0));
        lokeritera.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        lokeritera.setText("LOKER ITERA");

        javax.swing.GroupLayout bcklockerLayout = new javax.swing.GroupLayout(bcklocker);
        bcklocker.setLayout(bcklockerLayout);
        bcklockerLayout.setHorizontalGroup(
            bcklockerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcklockerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lokeritera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bcklockerLayout.setVerticalGroup(
            bcklockerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcklockerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lokeritera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        register.add(bcklocker, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 410, -1));

        nadep.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        nadep.setForeground(new java.awt.Color(255, 255, 255));
        nadep.setText("Nama Depan");
        register.add(nadep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        almt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        almt.setForeground(new java.awt.Color(255, 255, 255));
        almt.setText("Alamat");
        register.add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        mail.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("Email");
        register.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        nabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        nabel.setForeground(new java.awt.Color(255, 255, 255));
        nabel.setText("Nama Belakang");
        register.add(nabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jekel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jekel.setForeground(new java.awt.Color(255, 255, 255));
        jekel.setText("Jenis Kelamin");
        register.add(jekel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        phon.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        phon.setForeground(new java.awt.Color(255, 255, 255));
        phon.setText("Telepon");
        register.add(phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        pass.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password");
        register.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        namablkng.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        namablkng.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(namablkng, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 240, 40));

        phone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 240, 40));

        namadep.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        namadep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(namadep, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 240, 40));

        alamatt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        alamatt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(alamatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, 40));

        emaill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emaill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 240, 40));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        register.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 240, 40));

        jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jenkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenkelActionPerformed(evt);
            }
        });
        register.add(jenkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 240, 40));

        usname1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        usname1.setForeground(new java.awt.Color(255, 255, 255));
        usname1.setText("Username");
        register.add(usname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        daftar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        daftar1.setText("DAFTAR");
        daftar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar1ActionPerformed(evt);
            }
        });
        register.add(daftar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 140, 40));

        pwdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwddActionPerformed(evt);
            }
        });
        register.add(pwdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 240, 40));
        register.add(repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 240, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        register.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, -1, -1));

        retype.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        retype.setForeground(new java.awt.Color(255, 255, 255));
        retype.setText("Retype Password");
        register.add(retype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        bckutama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Menu.jpg"))); // NOI18N
        register.add(bckutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(908, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenkelActionPerformed

    private void daftar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar1ActionPerformed
        // TODO add your handling code here:
       String nama_depan = namadep.getText();
       String nama_belakang = namablkng.getText();
       String email = emaill.getText();
       String alamat = alamatt.getText();
       String jenis_kelamin = jenkel.getActionCommand();
       String telepon = phone.getText();
       String username = uname.getText();
       String password = String.valueOf(pwdd.getPassword());
       String repassword = String.valueOf(repass.getPassword());
    
        PreparedStatement ps;
        String query = "INSERT INTO `register`(`nama_depan`, `nama_belakang`, `alamat`, `jenis_kelamin`, `email`, `telepon`, `username`, `password`) VALUES (?,?,?,?,?,?,?,?)";
        
        try {
            ps = koneksi.getKoneksi().prepareStatement(query);
            ps.setString(1, nama_depan);
            ps.setString(2, nama_belakang);
            ps.setString(3, alamat);
            ps.setString(4, jenis_kelamin);
            ps.setString(5, email);
            ps.setString(6, telepon);
            ps.setString(7, username);
            ps.setString(8, password);
            ps.setString(9, repassword);
            
            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "User baru ditambahkan");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Home ho = new Home();
        ho.setVisible(true);
        dispose();
    }//GEN-LAST:event_daftar1ActionPerformed

    private void pwddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwddActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        Menu nu = new Menu();
        nu.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatt;
    private javax.swing.JLabel almt;
    private javax.swing.JPanel bcklocker;
    private javax.swing.JLabel bckutama;
    private javax.swing.JLabel close;
    private javax.swing.JButton daftar1;
    private javax.swing.JTextField emaill;
    private javax.swing.JLabel jekel;
    private javax.swing.JComboBox<String> jenkel;
    private javax.swing.JLabel lokeritera;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel nabel;
    private javax.swing.JLabel nadep;
    private javax.swing.JTextField namablkng;
    private javax.swing.JTextField namadep;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel phon;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField pwdd;
    private javax.swing.JPanel register;
    private javax.swing.JPasswordField repass;
    private javax.swing.JLabel retype;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel usname1;
    // End of variables declaration//GEN-END:variables
}
